function login(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',uc='.cache.html',_='/',lb='//',cc='02E77B73CAB0D8CE8EA5A827D067A1E0',dc='311CBF890749BA84364170B4B1394DBE',ec='374C2B6CBC1D5B2353DD2D06E166A4AF',fc='45FA78D746DDEADF83901BB8DD1986BD',gc='4B76F4658B90D3F5C26A78A3F7AB67F9',hc='6B51C732F1A70BCCC1D084F99F0AE90B',ic='8BBE54AD5DF3C67DB864A2DC4DFFF458',jc='9054BE4D62645ACF4C26831F47A06C45',kc='9A515A5029B7134736C3BFEC7A877467',tc=':',pb='::',wc='<script defer="defer">login.onInjectionDone(\'login\')<\/script>',hb='<script id="',sb='=',$='?',lc='A8A0AD9F2988BBB36732A1C0EF66BF5D',mc='B967848093FF52370B5C6C83AFB4C516',ub='Bad handler "',nc='D0AFC225222D32149898BF6CD2D66B81',oc='D6F50A0FA4B057198C2694E1FCD2D060',pc='D99AFAF2AA969AE6CB59E0035BD3D783',vc='DOMContentLoaded',qc='E04BE5DF4EF8C2B9B91B2AB5CC514978',rc='E0E3CF3537E53A36ADB67876F2AAAF95',sc='EB1FF456C13C63F8C1DF9115E20B4EDF',jb='SCRIPT',gb='__gwt_marker_login',Db='android',Fb='android_tablet',kb='base',cb='baseUrl',T='begin',Lb='blackberry',S='bootstrap',bb='clear.cache.gif',rb='content',Mb='desktop',Y='end',Yb='gecko',Zb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',ac='hosted.html?login',Xb='ie6',Wb='ie8',Vb='ie9',yb='iframe',ab='img',Gb='ipad',Hb='ipad_retina',Ib='iphone',Jb='ipod',zb="javascript:''",_b='loadExternalRefs',Q='login',eb='login.nocache.js',ob='login::',mb='meta',Cb='mgwt.os',Eb='mobile',Nb='mobile.user.agent',Ob='mobilesafari',Bb='moduleRequested',X='moduleStartup',Ub='msie',nb='name',Pb='not_mobile',Rb='opera',Ab='position:absolute;width:0;height:0;border:none',Kb='retina',Tb='safari',db='script',bc='selectingPermutation',R='startup',fb='undefined',$b='unknown',Qb='user.agent',Sb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}login=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Db)!=-1){if(a.indexOf(Eb)!=-1){return Db}else{return Fb}}if(a.indexOf(Gb)!=-1){if(window.devicePixelRatio>=2){return Hb}return Gb}if(a.indexOf(Ib)!=-1||a.indexOf(Jb)!=-1){if(window.devicePixelRatio>=2){return Kb}return Ib}if(a.indexOf(Lb)!=-1){return Lb}return Mb}();return b}};v[Cb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};w[Nb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Ob:Pb};v[Nb]={mobilesafari:0,not_mobile:1};w[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;if(function(){return b.indexOf(Ub)!=-1&&n.documentMode>=9}())return Vb;if(function(){return b.indexOf(Ub)!=-1&&n.documentMode>=8}())return Wb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Xb;if(function(){return b.indexOf(Yb)!=-1}())return Zb;return $b};v[Qb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};login.onScriptLoad=function(){if(I){r=true;C()}};login.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:_b,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=ac;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:bc});if(!B()){try{G([Mb,Pb,Tb],cc);G([Hb,Ob,Tb],dc);G([Db,Pb,Tb],ec);G([Mb,Pb,Zb],fc);G([Gb,Ob,Tb],gc);G([Ib,Ob,Tb],hc);G([Lb,Ob,Tb],ic);G([Gb,Pb,Tb],jc);G([Kb,Ob,Tb],kc);G([Mb,Ob,Tb],lc);G([Ib,Pb,Tb],mc);G([Kb,Pb,Tb],nc);G([Fb,Ob,Tb],oc);G([Lb,Pb,Tb],pc);G([Db,Ob,Tb],qc);G([Fb,Pb,Tb],rc);G([Hb,Pb,Tb],sc);K=x[H(Cb)][H(Nb)][H(Qb)];var M=K.indexOf(tc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+uc}catch(a){return}}var N;function O(){if(!s){s=true;C();if(n.removeEventListener){n.removeEventListener(vc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(vc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:_b,millis:(new Date).getTime(),type:T});n.write(wc)}
login();